### ISSUE TITLE
jenkins initial configuration fail due to "started by anonymous user"

### ISSUE THREAD

**Issue by BoPeng** [hms-dbmi/pic-sure-all-in-one#47]
<img width="1899" alt="image" src="https://user-images.githubusercontent.com/9889312/211940299-446532e9-75aa-49a9-b09d-7f6bd4b8f081.png">

Not sure if I need to restart from scratch.

**Comment by BoPeng** [comment]
I uninstall and re-installed `PIC-SURE` and this time jenkins starts as `admin`. I ran the iniitial config and build step and the step has been executing for more than 12 hours. I am not sure if the process has been stalled,

<img width="1805" alt="image" src="https://user-images.githubusercontent.com/9889312/212095962-56334144-c394-41c6-a7ef-39e1ca850ced.png">

**Comment by BoPeng** [comment]
We started from a fresh VM and get passed the initial configuration step. However, the email address cannot be used to login, not sure where to check. Note that  re-running in jenkins "set admin email" does not seem to help.

<img width="1695" alt="image" src="https://user-images.githubusercontent.com/9889312/212144907-e0285b0a-e5a4-4d04-8c54-c5a4b6026663.png">

**Comment by JamesPeck** [comment]
Hi @BoPeng can you please share the logs that show once you login. They can be found in the wildfly docker. `sudo docker logs -f wildfly`
You may also see something in the network tab in devtools for the authorization call.

**Comment by BoPeng** [comment]
```
19:37:53,884 WARN  [edu.harvard.hms.dbmi.avillach.auth.service.auth.AuthenticationService] (default task-1) Failed to authenticate.  Retrying
19:37:54,109 WARN  [org.apache.http.client.protocol.ResponseProcessCookies] (default task-1) Invalid cookie header: "Set-Cookie: did=s%3Av0%3A9b90c950-92b0-11ed-b403-5b6a74c724fa.a0ycCoueVg%2FhkP60C1YDaMJamUeoSiOAj%2BJ1jXWzL3Q; Max-Age=31557600; Path=/; Expires=Sat, 13 Jan 2024 01:37:54 GMT; HttpOnly; Secure; SameSite=None". Invalid 'expires' attribute: Sat, 13 Jan 2024 01:37:54 GMT
19:37:54,110 WARN  [org.apache.http.client.protocol.ResponseProcessCookies] (default task-1) Invalid cookie header: "Set-Cookie: did_compat=s%3Av0%3A9b90c950-92b0-11ed-b403-5b6a74c724fa.a0ycCoueVg%2FhkP60C1YDaMJamUeoSiOAj%2BJ1jXWzL3Q; Max-Age=31557600; Path=/; Expires=Sat, 13 Jan 2024 01:37:54 GMT; HttpOnly; Secure". Invalid 'expires' attribute: Sat, 13 Jan 2024 01:37:54 GMT
19:37:54,110 ERROR [edu.harvard.hms.dbmi.avillach.auth.service.auth.AuthenticationService] (default task-1) getToken() cannot find user_id by retrieveUserInfo(), return json response: {"sub":"google-oauth2|107783506330274448378","given_name":"Bo","family_name":"Peng","nickname":"ictr.bpeng","name":"Bo Peng","picture":"https://lh3.googleusercontent.com/a/AEdFTp5inL92TTlOLDTFK-jdH5tHTX0BkcDT2ozHLHw4=s96-c","locale":"en","updated_at":"2023-01-12T19:37:53.163Z","email":"ictr.bpeng@gmail.com","email_verified":true}
```

**Comment by BoPeng** [comment]
```
mysql> select * from user;
+------------------------------------+----------------+----------------------------------+-------------+------------------------------------+----------------------+------------------+---------+----------------------+-----------------+
| uuid                               | auth0_metadata | general_metadata                 | acceptedTOS | connectionId                       | email                | matched          | subject | is_active            | long_term_token |
+------------------------------------+----------------+----------------------------------+-------------+------------------------------------+----------------------+------------------+---------+----------------------+-----------------+
| 0x1CB5E16A75E54F229C141507DAE157F4 | NULL           | {"email":"ictr.bpeng@gmail.com"} | NULL        | 0x97FD002DC366B0D8420F998F885D0ED7 | ictr.bpeng@gmail.com | 0x00             | NULL    | 0x01                 | NULL            |
| 0x2C622AB4A401470AB6F770D45751F6FD | NULL           | {"email":"ictrbpeng@gmail.com"}  | NULL        | 0x97FD002DC366B0D8420F998F885D0ED7 | ictrbpeng@gmail.com  | 0x00             | NULL    | 0x01                 | NULL            |
| 0x9F422202EAF34F45B87010E2505AC226 | NULL           | {"email":"ictr.bpeng@gmail.com"} | NULL        | 0x97FD002DC366B0D8420F998F885D0ED7 | ictr.bpeng@gmail.com | 0x00             | NULL    | 0x01                 | NULL            |
| 0xBA43730811D14E44B339ABB33D61513E | NULL           | {"email":"ictr.bpeng@gmail.com"} | NULL        | 0x97FD002DC366B0D8420F998F885D0ED7 | ictr.bpeng@gmail.com | 0x00             | NULL    | 0x01                 | NULL            |
+------------------------------------+----------------+----------------------------------+-------------+------------------------------------+----------------------+------------------+---------+----------------------+-----------------+
4 rows in set (0.00 sec)
```

**Comment by JamesPeck** [comment]
That error usually occurs when Auth0 isn't configured as pic-sure expects. Are you using your own Auth0 connection? Can you please check to make sure that the following settings are turned OFF:
- Use Auth0 instead of the IdP to do Single Sign On (under Application Properties)
- OIDC (Advanced -> OAuth)

**Comment by BoPeng** [comment]
I did not touch SSO and not sure where to set the IdP. I have turned off ODIC. I still get the same authentication error, where nothing appears to be wrong for the login according to auth0 dashboard

![image](https://user-images.githubusercontent.com/9889312/212423743-24473cea-7822-47bd-920f-212236902396.png)


Can we have a zoom meeting so that I can show you my auth0 dashboard?

**Comment by JamesPeck** [comment]
@BoPeng We can set something up. In the meantime, these settings are under the application section not users. 
So the url would be something like: https://manage.auth0.com/dashboard/us/[your-organization-name]/applications/[your-client-id]/settings
This is the same location where you would have had to put your call back url.

**Comment by BoPeng** [comment]
@JamesPeck I looked under applications but could not find the SSO setting so I guess a zoom meeting is our best option now. I am available any time today except for lunch time (noon to 1pm CST) so please send an invite to bo.peng@bcm.edu if you are available.

**Comment by BoPeng** [comment]
According to the auth0 documentation: https://auth0.com/docs/get-started/applications/application-settings

<img width="1201" alt="image" src="https://user-images.githubusercontent.com/9889312/213544880-6ed86f21-5910-4554-93f3-bbf57b68e61d.png">

I do not quite understand what it says, @JamesPeck do you know if this option matters?

**Comment by BoPeng** [comment]
Also, I do not know if it matters but I chose "Java EE" as the technology for this application.

**Comment by dmpillion** [comment]
User has reported that this issue is resolved. Closing this issue.

**Comment by dmpillion** [comment]
User has reported that this issue is resolved. Closing this issue.
